language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # this needs to be installed in the root environment
  - conda install conda-build
  # Useful for debugging any issues with conda
  - conda info -a

  # create conda package and upload it to anaconda, only on stable branches
  - mkdir dist
  - conda build --python $TRAVIS_PYTHON_VERSION build_tools/conda-recipe --quiet
  - python build_tools/move-conda-package.py build_tools/conda-recipe
  - ls dist
  - conda install --quiet --yes anaconda-client
  - anaconda -t $ANACONDA_TOKEN upload dist/*.tar.bz2 --user scikit-learn-contrib

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy nose cython scikit-learn anaconda-client
  - source activate test-environment

  - make all
script:
- nosetests -v